`timescale 1ns/1ps 
// Generated by Cadence Genus(TM) Synthesis Solution 19.14-s108_1
// Generated on: Jan  5 2026 12:51:19 WET (Jan  5 2026 12:51:19 UTC)

// Verification Directory fv/top_module 

module top_module(clock, reset, bist_start, s, dv, l_in, test_in,
     pass_nfail, bist_end, cut_fz_L, cut_lclk, cut_read_a,
     cut_test_out);
  input clock, reset, bist_start, s, dv, l_in;
  input [1:0] test_in;
  output pass_nfail, bist_end, cut_fz_L, cut_lclk;
  output [4:0] cut_read_a;
  output [1:0] cut_test_out;
  wire clock, reset, bist_start, s, dv, l_in;
  wire [1:0] test_in;
  wire pass_nfail, bist_end, cut_fz_L, cut_lclk;
  wire [4:0] cut_read_a;
  wire [1:0] cut_test_out;
  wire [2:0] cut_inst_cur;
  wire [2:0] controller_inst_state;
  wire [10:0] controller_inst_cnt_m;
  wire [4:0] controller_inst_cnt_n;
  wire [7:0] lfsr_inst_shift_bits;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       UNCONNECTED3, UNCONNECTED4, UNCONNECTED5, UNCONNECTED6;
  wire UNCONNECTED7, UNCONNECTED8, UNCONNECTED9, UNCONNECTED10,
       UNCONNECTED11, UNCONNECTED12, UNCONNECTED13, UNCONNECTED14;
  wire UNCONNECTED15, UNCONNECTED16, UNCONNECTED17, UNCONNECTED18,
       UNCONNECTED19, UNCONNECTED20, UNCONNECTED21, UNCONNECTED22;
  wire UNCONNECTED23, UNCONNECTED24, UNCONNECTED25, UNCONNECTED26,
       UNCONNECTED27, UNCONNECTED28, UNCONNECTED29, UNCONNECTED30;
  wire controller_inst_prev_bist_start, cut_inst_n_0, cut_inst_n_1,
       cut_inst_n_2, cut_inst_n_3, cut_inst_n_4, cut_inst_n_6,
       cut_inst_n_7;
  wire cut_inst_n_8, cut_inst_n_9, cut_inst_n_10, cut_inst_n_11,
       cut_inst_n_12, cut_inst_n_33, cut_inst_n_44, cut_inst_n_46;
  wire cut_inst_n_48, cut_inst_n_49, cut_inst_n_52, cut_inst_n_53,
       cut_inst_n_57, cut_inst_n_59, cut_inst_n_62, cut_inst_n_68;
  wire cut_inst_n_70, cut_inst_n_72, cut_inst_out3, cut_inst_out4,
       \misr_inst_signature[0]_126 , \misr_inst_signature[1]_127 ,
       \misr_inst_signature[2]_128 , \misr_inst_signature[3]_129 ;
  wire \misr_inst_signature[4]_130 , \misr_inst_signature[5]_131 ,
       \misr_inst_signature[6]_132 , \misr_inst_signature[7]_133 ,
       \misr_inst_signature[8]_134 , \misr_inst_signature[9]_135 ,
       \misr_inst_signature[10]_136 , \misr_inst_signature[11]_137 ;
  wire \misr_inst_signature[12]_138 , \misr_inst_signature[13]_139 ,
       \misr_inst_signature[14]_140 , \misr_inst_signature[15]_141 ,
       n_0, n_1, n_2, n_3;
  wire n_4, n_5, n_6, n_7, n_8, n_9, n_10, n_11;
  wire n_12, n_13, n_14, n_15, n_16, n_17, n_18, n_19;
  wire n_20, n_21, n_22, n_23, n_24, n_25, n_26, n_27;
  wire n_28, n_29, n_30, n_31, n_32, n_33, n_34, n_35;
  wire n_36, n_37, n_38, n_39, n_40, n_41, n_42, n_43;
  wire n_44, n_45, n_46, n_47, n_48, n_49, n_50, n_51;
  wire n_52, n_53, n_54, n_55, n_56, n_57, n_58, n_59;
  wire n_60, n_61, n_62, n_63, n_64, n_65, n_66, n_67;
  wire n_68, n_69, n_70, n_71, n_72, n_73, n_74, n_75;
  wire n_76, n_77, n_78, n_79, n_80, n_81, n_82, n_83;
  wire n_84, n_85, n_86, n_87, n_88, n_89, n_90, n_91;
  wire n_92, n_93, n_94, n_95, n_96, n_97, n_98, n_99;
  wire n_100, n_101, n_102, n_103, n_104, n_105, n_106, n_107;
  wire n_108, n_109, n_110, n_111, n_112, n_113, n_114, n_115;
  wire n_116, n_117, n_118, n_119, n_120, n_121, n_122, n_123;
  wire n_124, n_125, n_126, n_127, n_128, n_129, n_130, n_131;
  wire n_132, n_133, n_134, n_135, n_136, n_137, n_138, n_139;
  wire n_140, n_141, n_142, n_143, n_144, n_145, n_146, n_147;
  wire n_148, n_149, n_150, n_151, n_152, n_153, n_154, n_155;
  wire n_156, n_157, n_158, n_159, n_160, n_161, n_162, n_163;
  wire n_164, n_165, n_166, n_167, n_168, n_169, n_170, n_171;
  wire n_172, n_173, n_174, n_175, n_176, n_177, n_178, n_179;
  wire n_180, n_181, n_182, n_183, n_184, n_185, n_186, n_187;
  wire n_188, n_189, n_190, n_191, n_192, n_193, n_194, n_195;
  wire n_196, n_197, n_198, n_199, n_200, n_201, n_202, n_203;
  wire n_204, n_205, n_206, n_207, n_208, n_209, n_210, n_211;
  wire n_212, n_213, n_214, n_215, n_216, n_217, n_218, n_219;
  wire n_220, n_221, n_222, n_223, n_224, n_225, n_226, n_227;
  wire n_228, n_229, n_230, n_231, n_232, n_233, n_234, n_235;
  wire n_236, n_237, scan_chain_in, scan_chain_out;
  DFS3 \cut_inst_cur_reg[0] (.C (clock), .D (cut_inst_n_72), .SD
       (scan_chain_in), .SE (n_234), .Q (cut_inst_cur[0]), .QN
       (cut_inst_n_12));
  DFS3 \cut_inst_cur_reg[1] (.C (clock), .D (cut_inst_n_70), .SD
       (cut_inst_n_12), .SE (n_234), .Q (cut_inst_cur[1]), .QN
       (cut_inst_n_11));
  DFS3 \cut_inst_cur_reg[2] (.C (clock), .D (cut_inst_n_68), .SD
       (cut_inst_n_11), .SE (n_234), .Q (cut_inst_cur[2]), .QN
       (cut_inst_n_10));
  DFS3 cut_inst_lclk_i_reg(.C (clock), .D (cut_inst_n_52), .SD
       (cut_inst_n_10), .SE (n_234), .Q (cut_lclk), .QN (cut_inst_n_6));
  DFS3 cut_inst_out3_reg(.C (clock), .D (cut_inst_n_33), .SD
       (cut_inst_n_6), .SE (n_234), .Q (cut_inst_out3), .QN
       (cut_inst_n_0));
  DFS3 cut_inst_out4_reg(.C (clock), .D (cut_inst_n_57), .SD
       (cut_inst_n_0), .SE (n_234), .Q (cut_inst_out4), .QN
       (cut_inst_n_8));
  DFS3 \cut_inst_read_a_i_reg[0] (.C (clock), .D (cut_inst_n_46), .SD
       (cut_inst_n_8), .SE (n_234), .Q (cut_read_a[0]), .QN
       (cut_inst_n_1));
  DFS3 \cut_inst_read_a_i_reg[1] (.C (clock), .D (cut_inst_n_48), .SD
       (cut_inst_n_1), .SE (n_234), .Q (cut_read_a[1]), .QN
       (cut_inst_n_2));
  DFS3 \cut_inst_read_a_i_reg[2] (.C (clock), .D (cut_inst_n_44), .SD
       (cut_inst_n_2), .SE (n_234), .Q (cut_read_a[2]), .QN
       (cut_inst_n_3));
  DFS3 \cut_inst_read_a_i_reg[3] (.C (clock), .D (cut_inst_n_59), .SD
       (cut_inst_n_3), .SE (n_234), .Q (cut_read_a[3]), .QN
       (cut_inst_n_7));
  DFS3 \cut_inst_read_a_i_reg[4] (.C (clock), .D (cut_inst_n_62), .SD
       (cut_inst_n_7), .SE (n_234), .Q (cut_read_a[4]), .QN
       (cut_inst_n_9));
  DFS3 \cut_inst_test_out_i_reg[0] (.C (clock), .D (cut_inst_n_49), .SD
       (cut_inst_n_9), .SE (n_234), .Q (cut_test_out[0]), .QN
       (cut_inst_n_4));
  DFS3 \cut_inst_test_out_i_reg[1] (.C (clock), .D (cut_inst_n_53), .SD
       (cut_inst_n_4), .SE (n_234), .Q (cut_test_out[1]), .QN
       (scan_chain_out));
  INV3 g1376(.A (n_235), .Q (n_234));
  INV0 g1380(.A (\misr_inst_signature[13]_139 ), .Q (n_233));
  INV0 g1378(.A (\misr_inst_signature[9]_135 ), .Q (n_232));
  INV0 g1379(.A (\misr_inst_signature[5]_131 ), .Q (n_231));
  INV0 g1377(.A (\misr_inst_signature[2]_128 ), .Q (n_230));
  OAI311 g2260__2398(.A (l_in), .B (n_197), .C (n_203), .D (n_229), .Q
       (cut_inst_n_72));
  AOI221 g2261__5107(.A (n_228), .B (n_182), .C (n_220), .D (dv), .Q
       (n_229));
  AOI211 g2262__6260(.A (n_226), .B (n_195), .C (reset), .Q
       (cut_inst_n_62));
  INV3 g2263(.A (n_227), .Q (n_228));
  OAI212 g2264__4319(.A (cut_inst_cur[0]), .B (n_225), .C (n_212), .Q
       (n_227));
  ADD22 g2265__8428(.A (n_223), .B (n_178), .CO (n_225), .S (n_226));
  AOI211 g2266__5526(.A (n_224), .B (n_195), .C (reset), .Q
       (cut_inst_n_59));
  OAI211 g2267__6783(.A (dv), .B (n_221), .C (n_222), .Q
       (cut_inst_n_68));
  ADD22 g2268__3680(.A (n_217), .B (n_171), .CO (n_223), .S (n_224));
  NAND22 g2269__1617(.A (n_212), .B (n_219), .Q (n_222));
  AOI311 g2270__2802(.A (n_175), .B (n_181), .C (n_202), .D (n_220), .Q
       (n_221));
  OAI311 g2271__1705(.A (cut_inst_cur[1]), .B (n_213), .C (n_211), .D
       (n_210), .Q (cut_inst_n_70));
  NOR21 g2272__5122(.A (n_218), .B (n_198), .Q (cut_inst_n_44));
  NOR21 g2273__8246(.A (n_198), .B (n_214), .Q (cut_inst_n_52));
  NOR31 g2274__7098(.A (n_205), .B (n_207), .C (reset), .Q
       (cut_inst_n_33));
  OAI212 g2275__6131(.A (cut_inst_cur[2]), .B (n_184), .C (n_215), .Q
       (n_219));
  OAI212 g2276__1881(.A (reset), .B (n_206), .C (n_216), .Q
       (cut_inst_n_53));
  NOR40 g2277__5115(.A (cut_inst_cur[0]), .B (n_175), .C (n_174), .D
       (n_203), .Q (n_220));
  ADD22 g2278__7482(.A (n_187), .B (n_172), .CO (n_217), .S (n_218));
  NAND22 g2279__4733(.A (n_208), .B (cut_test_out[1]), .Q (n_216));
  NAND22 g2280__6161(.A (n_213), .B (n_182), .Q (n_215));
  OAI311 g2281__9315(.A (reset), .B (n_197), .C (n_199), .D (n_209), .Q
       (cut_inst_n_49));
  XNR21 g2282__9945(.A (cut_lclk), .B (n_204), .Q (n_214));
  INV2 g2283(.A (n_212), .Q (n_211));
  OAI212 g2284__2883(.A (n_200), .B (n_196), .C (n_202), .Q (n_210));
  NAND22 g2285__2346(.A (n_204), .B (cut_inst_cur[0]), .Q (n_213));
  AOI211 g2286__1666(.A (cut_inst_out3), .B (cut_inst_out4), .C
       (n_203), .Q (n_212));
  INV2 g2287(.A (n_208), .Q (n_209));
  XNR21 g2288__7410(.A (cut_test_out[1]), .B (n_201), .Q (n_207));
  IMUX21 g2289__6417(.A (n_201), .B (n_185), .S (n_197), .Q (n_206));
  XNR21 g2290__5477(.A (cut_test_out[0]), .B (n_199), .Q (n_205));
  NOR31 g2291__2398(.A (n_196), .B (cut_test_out[0]), .C (reset), .Q
       (n_208));
  NOR21 g2292__5107(.A (cut_read_a[0]), .B (n_198), .Q (cut_inst_n_46));
  NOR21 g2293__6260(.A (n_190), .B (n_198), .Q (cut_inst_n_48));
  INV2 g2294(.A (n_203), .Q (n_202));
  NOR40 g2295__4319(.A (n_193), .B (n_189), .C (n_191), .D (n_192), .Q
       (pass_nfail));
  NOR40 g2296__8428(.A (cut_read_a[1]), .B (n_177), .C (cut_read_a[2]),
       .D (n_186), .Q (n_204));
  NAND31 g2297__5526(.A (n_235), .B (n_170), .C (s), .Q (n_203));
  NOR21 g2298__6783(.A (dv), .B (n_195), .Q (n_200));
  NAND22 g2299__3680(.A (n_235), .B (test_in[1]), .Q (n_201));
  INV2 g2300(.A (n_197), .Q (n_196));
  NAND22 g2301__1617(.A (n_235), .B (test_in[0]), .Q (n_199));
  NAND22 g2302__2802(.A (n_195), .B (n_170), .Q (n_198));
  OAI2111 g2303__1705(.A (cut_inst_cur[0]), .B (cut_inst_cur[1]), .C
       (n_184), .D (n_175), .Q (n_197));
  INV3 g2304(.A (n_194), .Q (n_235));
  NOR20 g2305__5122(.A (n_180), .B (n_237), .Q (bist_end));
  NOR21 g2306__8246(.A (cut_inst_cur[0]), .B (n_183), .Q (cut_fz_L));
  NAND22 g2307__7098(.A (n_184), .B (n_183), .Q (n_195));
  NOR21 g2308__6131(.A (controller_inst_state[0]), .B (n_236), .Q
       (n_194));
  INV2 g2309(.A (n_188), .Q (n_193));
  NAND40 g2310__1881(.A (n_232), .B (\misr_inst_signature[10]_136 ), .C
       (\misr_inst_signature[11]_137 ), .D
       (\misr_inst_signature[12]_138 ), .Q (n_192));
  NAND40 g2311__5115(.A (n_230), .B (\misr_inst_signature[1]_127 ), .C
       (\misr_inst_signature[3]_129 ), .D (\misr_inst_signature[4]_130
       ), .Q (n_191));
  AOI211 g2312__7482(.A (cut_read_a[1]), .B (cut_read_a[0]), .C
       (n_187), .Q (n_190));
  NAND40 g2313__4733(.A (n_233), .B (\misr_inst_signature[14]_140 ), .C
       (\misr_inst_signature[0]_126 ), .D (\misr_inst_signature[15]_141
       ), .Q (n_189));
  NOR40 g2314__6161(.A (\misr_inst_signature[6]_132 ), .B
       (\misr_inst_signature[8]_134 ), .C (\misr_inst_signature[7]_133
       ), .D (n_231), .Q (n_188));
  NAND22 g2315__9315(.A (cut_read_a[3]), .B (cut_read_a[4]), .Q
       (n_186));
  NOR21 g2316__9945(.A (cut_test_out[1]), .B (n_176), .Q (n_185));
  DF3 controller_inst_prev_bist_start_reg(.C (clock), .D (bist_start),
       .Q (controller_inst_prev_bist_start), .QN (UNCONNECTED));
  NAND22 g2318__2883(.A (n_179), .B (controller_inst_state[0]), .Q
       (n_237));
  NOR21 g2319__2346(.A (cut_read_a[0]), .B (cut_read_a[1]), .Q (n_187));
  INV2 g2320(.A (n_183), .Q (n_182));
  NOR21 g2321__1666(.A (reset), .B (n_173), .Q (cut_inst_n_57));
  NOR21 g2322__7410(.A (cut_inst_cur[0]), .B (cut_inst_cur[1]), .Q
       (n_181));
  NAND22 g2323__6417(.A (n_180), .B (controller_inst_state[1]), .Q
       (n_236));
  NAND22 g2324__5477(.A (cut_inst_cur[1]), .B (cut_inst_cur[0]), .Q
       (n_184));
  NAND22 g2325__2398(.A (n_174), .B (cut_inst_cur[2]), .Q (n_183));
  CLKIN3 g2326(.A (controller_inst_state[2]), .Q (n_180));
  CLKIN2 g2327(.A (controller_inst_state[1]), .Q (n_179));
  INV2 g2328(.A (cut_read_a[4]), .Q (n_178));
  INV2 g2329(.A (cut_read_a[0]), .Q (n_177));
  CLKIN2 g2330(.A (cut_test_out[0]), .Q (n_176));
  INV3 g2331(.A (cut_inst_cur[2]), .Q (n_175));
  INV2 g2332(.A (cut_inst_cur[1]), .Q (n_174));
  INV2 g2333(.A (cut_inst_out3), .Q (n_173));
  INV3 g2334(.A (cut_read_a[2]), .Q (n_172));
  INV3 g2335(.A (cut_read_a[3]), .Q (n_171));
  INV2 g2336(.A (reset), .Q (n_170));
  DF3 \controller_inst_cnt_m_reg[0] (.C (clock), .D (n_114), .Q
       (controller_inst_cnt_m[0]), .QN (UNCONNECTED0));
  JK3 \controller_inst_cnt_m_reg[1] (.C (clock), .J (n_95), .K (n_112),
       .Q (controller_inst_cnt_m[1]), .QN (n_7));
  DF3 \controller_inst_cnt_m_reg[2] (.C (clock), .D (n_152), .Q
       (controller_inst_cnt_m[2]), .QN (UNCONNECTED1));
  DF3 \controller_inst_cnt_m_reg[3] (.C (clock), .D (n_156), .Q
       (controller_inst_cnt_m[3]), .QN (UNCONNECTED2));
  DF3 \controller_inst_cnt_m_reg[4] (.C (clock), .D (n_155), .Q
       (controller_inst_cnt_m[4]), .QN (n_10));
  DF3 \controller_inst_cnt_m_reg[5] (.C (clock), .D (n_154), .Q
       (controller_inst_cnt_m[5]), .QN (UNCONNECTED3));
  DF3 \controller_inst_cnt_m_reg[6] (.C (clock), .D (n_153), .Q
       (controller_inst_cnt_m[6]), .QN (n_9));
  DF3 \controller_inst_cnt_m_reg[7] (.C (clock), .D (n_151), .Q
       (controller_inst_cnt_m[7]), .QN (UNCONNECTED4));
  DF3 \controller_inst_cnt_m_reg[8] (.C (clock), .D (n_162), .Q
       (controller_inst_cnt_m[8]), .QN (n_2));
  DF3 \controller_inst_cnt_m_reg[9] (.C (clock), .D (n_166), .Q
       (controller_inst_cnt_m[9]), .QN (UNCONNECTED5));
  DF3 \controller_inst_cnt_m_reg[10] (.C (clock), .D (n_169), .Q
       (controller_inst_cnt_m[10]), .QN (UNCONNECTED6));
  DF3 \controller_inst_cnt_n_reg[0] (.C (clock), .D (n_126), .Q
       (controller_inst_cnt_n[0]), .QN (UNCONNECTED7));
  DF3 \controller_inst_cnt_n_reg[1] (.C (clock), .D (n_159), .Q
       (controller_inst_cnt_n[1]), .QN (UNCONNECTED8));
  DF3 \controller_inst_cnt_n_reg[2] (.C (clock), .D (n_167), .Q
       (controller_inst_cnt_n[2]), .QN (UNCONNECTED9));
  DF3 \controller_inst_cnt_n_reg[3] (.C (clock), .D (n_165), .Q
       (controller_inst_cnt_n[3]), .QN (UNCONNECTED10));
  DF3 \controller_inst_state_reg[0] (.C (clock), .D (n_127), .Q
       (controller_inst_state[0]), .QN (UNCONNECTED11));
  DF3 \controller_inst_state_reg[1] (.C (clock), .D (n_65), .Q
       (controller_inst_state[1]), .QN (UNCONNECTED12));
  DF3 \controller_inst_state_reg[2] (.C (clock), .D (n_74), .Q
       (controller_inst_state[2]), .QN (n_8));
  DF3 \lfsr_inst_shift_bits_reg[0] (.C (clock), .D (n_123), .Q
       (lfsr_inst_shift_bits[0]), .QN (UNCONNECTED13));
  DF3 \lfsr_inst_shift_bits_reg[1] (.C (clock), .D (n_84), .Q
       (lfsr_inst_shift_bits[1]), .QN (UNCONNECTED14));
  DF3 \lfsr_inst_shift_bits_reg[2] (.C (clock), .D (n_89), .Q
       (lfsr_inst_shift_bits[2]), .QN (UNCONNECTED15));
  DF3 \lfsr_inst_shift_bits_reg[3] (.C (clock), .D (n_83), .Q
       (lfsr_inst_shift_bits[3]), .QN (UNCONNECTED16));
  DF3 \lfsr_inst_shift_bits_reg[4] (.C (clock), .D (n_90), .Q
       (lfsr_inst_shift_bits[4]), .QN (UNCONNECTED17));
  DF3 \lfsr_inst_shift_bits_reg[5] (.C (clock), .D (n_82), .Q
       (lfsr_inst_shift_bits[5]), .QN (UNCONNECTED18));
  DF3 \lfsr_inst_shift_bits_reg[6] (.C (clock), .D (n_91), .Q
       (lfsr_inst_shift_bits[6]), .QN (UNCONNECTED19));
  DF3 \lfsr_inst_shift_bits_reg[7] (.C (clock), .D (n_81), .Q
       (scan_chain_in), .QN (UNCONNECTED20));
  DF3 \misr_inst_signature_reg[0] (.C (clock), .D (n_75), .Q
       (\misr_inst_signature[0]_126 ), .QN (n_4));
  DF3 \misr_inst_signature_reg[1] (.C (clock), .D (n_134), .Q
       (\misr_inst_signature[1]_127 ), .QN (UNCONNECTED21));
  DF3 \misr_inst_signature_reg[2] (.C (clock), .D (n_133), .Q
       (\misr_inst_signature[2]_128 ), .QN (UNCONNECTED22));
  DF3 \misr_inst_signature_reg[3] (.C (clock), .D (n_132), .Q
       (\misr_inst_signature[3]_129 ), .QN (UNCONNECTED23));
  DF3 \misr_inst_signature_reg[4] (.C (clock), .D (n_135), .Q
       (\misr_inst_signature[4]_130 ), .QN (UNCONNECTED24));
  DF3 \misr_inst_signature_reg[5] (.C (clock), .D (n_130), .Q
       (\misr_inst_signature[5]_131 ), .QN (UNCONNECTED25));
  DF3 \misr_inst_signature_reg[6] (.C (clock), .D (n_129), .Q
       (\misr_inst_signature[6]_132 ), .QN (UNCONNECTED26));
  DF3 \misr_inst_signature_reg[7] (.C (clock), .D (n_128), .Q
       (\misr_inst_signature[7]_133 ), .QN (UNCONNECTED27));
  DF3 \misr_inst_signature_reg[8] (.C (clock), .D (n_120), .Q
       (\misr_inst_signature[8]_134 ), .QN (UNCONNECTED28));
  DF3 \misr_inst_signature_reg[9] (.C (clock), .D (n_124), .Q
       (\misr_inst_signature[9]_135 ), .QN (n_5));
  DF3 \misr_inst_signature_reg[10] (.C (clock), .D (n_85), .Q
       (\misr_inst_signature[10]_136 ), .QN (n_1));
  DF3 \misr_inst_signature_reg[11] (.C (clock), .D (n_78), .Q
       (\misr_inst_signature[11]_137 ), .QN (n_3));
  DF3 \misr_inst_signature_reg[12] (.C (clock), .D (n_77), .Q
       (\misr_inst_signature[12]_138 ), .QN (n_6));
  DF3 \misr_inst_signature_reg[13] (.C (clock), .D (n_76), .Q
       (\misr_inst_signature[13]_139 ), .QN (UNCONNECTED29));
  DF3 \misr_inst_signature_reg[14] (.C (clock), .D (n_80), .Q
       (\misr_inst_signature[14]_140 ), .QN (n_0));
  DF3 \misr_inst_signature_reg[15] (.C (clock), .D (n_79), .Q
       (\misr_inst_signature[15]_141 ), .QN (UNCONNECTED30));
  OAI311 g2593__5107(.A (n_96), .B (controller_inst_cnt_m[10]), .C
       (n_146), .D (n_168), .Q (n_169));
  OAI212 g2597__6260(.A (n_99), .B (n_161), .C
       (controller_inst_cnt_m[10]), .Q (n_168));
  OAI212 g2598__4319(.A (n_47), .B (n_149), .C (n_164), .Q (n_167));
  OAI311 g2599__8428(.A (n_96), .B (controller_inst_cnt_m[9]), .C
       (n_137), .D (n_163), .Q (n_166));
  OAI212 g2605__5526(.A (n_47), .B (n_148), .C (n_66), .Q (n_165));
  AOI221 g2606__6783(.A (n_149), .B (n_36), .C
       (controller_inst_cnt_n[2]), .D (n_35), .Q (n_164));
  NAND22 g2607__3680(.A (controller_inst_cnt_m[9]), .B (n_158), .Q
       (n_163));
  OAI311 g2608__1617(.A (n_96), .B (controller_inst_cnt_m[8]), .C
       (n_113), .D (n_157), .Q (n_162));
  CLKIN3 g2611(.A (n_160), .Q (n_161));
  NAND22 g2612__2802(.A (n_146), .B (n_72), .Q (n_160));
  NOR21 g2613__1705(.A (n_48), .B (n_150), .Q (n_159));
  NAND22 g2614__5122(.A (n_112), .B (n_141), .Q (n_158));
  NAND22 g2615__8246(.A (controller_inst_cnt_m[8]), .B (n_144), .Q
       (n_157));
  OAI311 g2617__7098(.A (n_96), .B (controller_inst_cnt_m[3]), .C
       (n_20), .D (n_145), .Q (n_156));
  OAI311 g2618__6131(.A (n_96), .B (controller_inst_cnt_m[4]), .C
       (n_34), .D (n_139), .Q (n_155));
  OAI311 g2619__1881(.A (n_96), .B (controller_inst_cnt_m[5]), .C
       (n_46), .D (n_138), .Q (n_154));
  OAI311 g2620__5115(.A (n_96), .B (controller_inst_cnt_m[6]), .C
       (n_73), .D (n_140), .Q (n_153));
  OAI311 g2621__7482(.A (n_96), .B (controller_inst_cnt_m[2]), .C
       (n_7), .D (n_143), .Q (n_152));
  OAI311 g2622__4733(.A (n_96), .B (controller_inst_cnt_m[7]), .C
       (n_98), .D (n_142), .Q (n_151));
  INV2 g2623(.A (n_147), .Q (n_150));
  INV2 g2624(.A (n_149), .Q (n_148));
  ADD22 g2625__6161(.A (n_93), .B (controller_inst_cnt_n[1]), .CO
       (n_149), .S (n_147));
  NAND22 g2636__9315(.A (controller_inst_cnt_m[3]), .B (n_121), .Q
       (n_145));
  NAND22 g2637__9945(.A (n_112), .B (n_131), .Q (n_144));
  NAND22 g2638__2883(.A (controller_inst_cnt_m[2]), .B (n_116), .Q
       (n_143));
  NAND22 g2639__2346(.A (controller_inst_cnt_m[7]), .B (n_119), .Q
       (n_142));
  NAND22 g2640__1666(.A (n_137), .B (n_72), .Q (n_141));
  NAND22 g2641__7410(.A (controller_inst_cnt_m[6]), .B (n_117), .Q
       (n_140));
  NAND22 g2642__6417(.A (controller_inst_cnt_m[4]), .B (n_118), .Q
       (n_139));
  NAND22 g2643__5477(.A (controller_inst_cnt_m[5]), .B (n_125), .Q
       (n_138));
  NAND22 g2644__2398(.A (n_136), .B (controller_inst_cnt_m[9]), .Q
       (n_146));
  INV2 g2647(.A (n_136), .Q (n_137));
  NOR21 g2648__5107(.A (n_70), .B (n_103), .Q (n_135));
  NOR21 g2649__6260(.A (n_70), .B (n_106), .Q (n_134));
  NOR21 g2650__4319(.A (n_70), .B (n_105), .Q (n_133));
  NOR21 g2651__8428(.A (n_70), .B (n_111), .Q (n_132));
  NAND22 g2652__5526(.A (n_113), .B (n_72), .Q (n_131));
  NOR21 g2653__6783(.A (n_70), .B (n_102), .Q (n_130));
  NOR21 g2654__3680(.A (n_70), .B (n_101), .Q (n_129));
  NOR21 g2655__1617(.A (n_70), .B (n_100), .Q (n_128));
  NOR21 g2657__2802(.A (n_2), .B (n_113), .Q (n_136));
  INV3 g2658(.A (n_122), .Q (n_127));
  CLKIN2 g2659(.A (n_115), .Q (n_126));
  NAND22 g2660__1705(.A (n_112), .B (n_92), .Q (n_125));
  NOR21 g2661__5122(.A (n_70), .B (n_108), .Q (n_124));
  NAND22 g2662__8246(.A (n_110), .B (n_69), .Q (n_123));
  AOI2111 g2663__7098(.A (n_234), .B (n_72), .C (n_38), .D (n_42), .Q
       (n_122));
  NAND22 g2664__6131(.A (n_112), .B (n_88), .Q (n_121));
  NOR21 g2665__1881(.A (n_70), .B (n_104), .Q (n_120));
  NAND22 g2666__5115(.A (n_112), .B (n_109), .Q (n_119));
  NAND22 g2667__7482(.A (n_112), .B (n_86), .Q (n_118));
  NAND22 g2668__4733(.A (n_112), .B (n_87), .Q (n_117));
  OAI212 g2669__6161(.A (n_71), .B (controller_inst_cnt_m[1]), .C
       (n_112), .Q (n_116));
  AOI221 g2670__9315(.A (n_94), .B (n_49), .C (n_33), .D (n_35), .Q
       (n_115));
  INV3 g2685(.A (n_107), .Q (n_114));
  IMUX21 g2686__9945(.A (n_57), .B (\misr_inst_signature[3]_129 ), .S
       (n_236), .Q (n_111));
  IMUX20 g2687__2883(.A (lfsr_inst_shift_bits[0]), .B (n_50), .S
       (n_234), .Q (n_110));
  NAND22 g2688__2346(.A (n_98), .B (n_72), .Q (n_109));
  IMUX21 g2689__1666(.A (n_51), .B (\misr_inst_signature[9]_135 ), .S
       (n_236), .Q (n_108));
  AOI311 g2690__7410(.A (n_15), .B (controller_inst_cnt_m[0]), .C
       (n_44), .D (n_99), .Q (n_107));
  IMUX21 g2691__6417(.A (n_59), .B (\misr_inst_signature[1]_127 ), .S
       (n_236), .Q (n_106));
  IMUX21 g2692__5477(.A (n_58), .B (\misr_inst_signature[2]_128 ), .S
       (n_236), .Q (n_105));
  IMUX21 g2693__2398(.A (n_52), .B (\misr_inst_signature[8]_134 ), .S
       (n_236), .Q (n_104));
  IMUX21 g2694__5107(.A (n_56), .B (\misr_inst_signature[4]_130 ), .S
       (n_236), .Q (n_103));
  IMUX21 g2695__6260(.A (n_60), .B (\misr_inst_signature[5]_131 ), .S
       (n_236), .Q (n_102));
  IMUX21 g2696__4319(.A (n_54), .B (\misr_inst_signature[6]_132 ), .S
       (n_236), .Q (n_101));
  IMUX21 g2697__8428(.A (n_53), .B (\misr_inst_signature[7]_133 ), .S
       (n_236), .Q (n_100));
  NAND22 g2699__5526(.A (n_97), .B (controller_inst_cnt_m[7]), .Q
       (n_113));
  AOI211 g2700__6783(.A (n_44), .B (n_15), .C (n_99), .Q (n_112));
  INV2 g2701(.A (n_97), .Q (n_98));
  INV2 g2702(.A (n_96), .Q (n_95));
  ADD22 g2703__3680(.A (n_33), .B (controller_inst_cnt_n[0]), .CO
       (n_93), .S (n_94));
  NAND22 g2704__1617(.A (n_46), .B (n_72), .Q (n_92));
  NAND22 g2705__2802(.A (n_29), .B (n_69), .Q (n_91));
  NAND22 g2706__1705(.A (n_27), .B (n_69), .Q (n_90));
  NAND22 g2707__5122(.A (n_25), .B (n_69), .Q (n_89));
  NAND22 g2708__8246(.A (n_20), .B (n_72), .Q (n_88));
  NAND22 g2709__7098(.A (n_73), .B (n_72), .Q (n_87));
  NAND22 g2710__6131(.A (n_34), .B (n_72), .Q (n_86));
  NOR21 g2711__1881(.A (n_71), .B (controller_inst_cnt_m[0]), .Q
       (n_99));
  NOR21 g2712__5115(.A (n_9), .B (n_73), .Q (n_97));
  NAND22 g2714__7482(.A (controller_inst_cnt_m[0]), .B (n_72), .Q
       (n_96));
  NOR21 g2715__4733(.A (n_70), .B (n_63), .Q (n_85));
  NOR21 g2716__6161(.A (n_70), .B (n_22), .Q (n_84));
  NOR21 g2717__9315(.A (n_70), .B (n_28), .Q (n_83));
  NOR21 g2718__9945(.A (n_70), .B (n_26), .Q (n_82));
  NOR21 g2719__2883(.A (n_70), .B (n_24), .Q (n_81));
  NOR21 g2720__2346(.A (n_70), .B (n_55), .Q (n_80));
  NOR21 g2721__1666(.A (n_70), .B (n_68), .Q (n_79));
  NOR21 g2722__7410(.A (n_70), .B (n_64), .Q (n_78));
  NOR21 g2723__6417(.A (n_70), .B (n_61), .Q (n_77));
  NOR21 g2724__5477(.A (n_70), .B (n_67), .Q (n_76));
  NOR21 g2725__2398(.A (n_70), .B (n_62), .Q (n_75));
  OAI222 g2726__5107(.A (n_43), .B (reset), .C (n_16), .D (n_39), .Q
       (n_74));
  INV3 g2727(.A (n_72), .Q (n_71));
  INV3 g2728(.A (n_70), .Q (n_69));
  IMUX30 g2729__6260(.A (\misr_inst_signature[14]_140 ), .B (n_0), .C
       (\misr_inst_signature[15]_141 ), .S0
       (\misr_inst_signature[15]_141 ), .S1 (n_236), .Q (n_68));
  IMUX30 g2730__4319(.A (\misr_inst_signature[12]_138 ), .B (n_6), .C
       (\misr_inst_signature[13]_139 ), .S0
       (\misr_inst_signature[13]_139 ), .S1 (n_236), .Q (n_67));
  OAI212 g2731__8428(.A (n_36), .B (n_35), .C
       (controller_inst_cnt_n[3]), .Q (n_66));
  OAI222 g2732__5526(.A (n_32), .B (reset), .C (n_236), .D (n_14), .Q
       (n_65));
  IMUX30 g2733__6783(.A (\misr_inst_signature[10]_136 ), .B (n_1), .C
       (\misr_inst_signature[11]_137 ), .S0
       (\misr_inst_signature[11]_137 ), .S1 (n_236), .Q (n_64));
  IMUX30 g2734__3680(.A (\misr_inst_signature[9]_135 ), .B (n_5), .C
       (\misr_inst_signature[10]_136 ), .S0
       (\misr_inst_signature[10]_136 ), .S1 (n_236), .Q (n_63));
  IMUX20 g2735__1617(.A (n_23), .B (\misr_inst_signature[0]_126 ), .S
       (n_236), .Q (n_62));
  IMUX30 g2736__2802(.A (\misr_inst_signature[11]_137 ), .B (n_3), .C
       (\misr_inst_signature[12]_138 ), .S0
       (\misr_inst_signature[12]_138 ), .S1 (n_236), .Q (n_61));
  NAND22 g2737__1705(.A (n_45), .B (controller_inst_cnt_m[5]), .Q
       (n_73));
  NOR21 g2738__5122(.A (reset), .B (n_44), .Q (n_72));
  NAND22 g2739__8246(.A (n_41), .B (n_12), .Q (n_70));
  XOR31 g2740__7098(.A (cut_read_a[2]), .B (\misr_inst_signature[4]_130
       ), .C (\misr_inst_signature[5]_131 ), .Q (n_60));
  XOR31 g2741__6131(.A (cut_fz_L), .B (\misr_inst_signature[1]_127 ),
       .C (\misr_inst_signature[0]_126 ), .Q (n_59));
  XOR31 g2742__1881(.A (cut_lclk), .B (\misr_inst_signature[1]_127 ),
       .C (\misr_inst_signature[2]_128 ), .Q (n_58));
  XOR31 g2743__5115(.A (cut_read_a[4]), .B (\misr_inst_signature[2]_128
       ), .C (\misr_inst_signature[3]_129 ), .Q (n_57));
  XOR31 g2744__7482(.A (cut_read_a[3]), .B (\misr_inst_signature[3]_129
       ), .C (\misr_inst_signature[4]_130 ), .Q (n_56));
  IMUX30 g2745__4733(.A (\misr_inst_signature[14]_140 ), .B (n_0), .C
       (\misr_inst_signature[14]_140 ), .S0
       (\misr_inst_signature[13]_139 ), .S1 (n_236), .Q (n_55));
  XOR31 g2746__6161(.A (cut_read_a[1]), .B (\misr_inst_signature[5]_131
       ), .C (\misr_inst_signature[6]_132 ), .Q (n_54));
  XOR31 g2747__9315(.A (cut_read_a[0]), .B (\misr_inst_signature[6]_132
       ), .C (\misr_inst_signature[7]_133 ), .Q (n_53));
  XOR31 g2748__9945(.A (cut_test_out[1]), .B
       (\misr_inst_signature[7]_133 ), .C (\misr_inst_signature[8]_134
       ), .Q (n_52));
  XOR31 g2749__2883(.A (cut_test_out[0]), .B
       (\misr_inst_signature[9]_135 ), .C (\misr_inst_signature[8]_134
       ), .Q (n_51));
  XOR31 g2750__2346(.A (lfsr_inst_shift_bits[3]), .B
       (lfsr_inst_shift_bits[4]), .C (n_21), .Q (n_50));
  INV2 g2751(.A (n_48), .Q (n_49));
  INV2 g2752(.A (n_45), .Q (n_46));
  NOR21 g2753__1666(.A (n_40), .B (n_36), .Q (n_48));
  NAND22 g2754__7410(.A (controller_inst_cnt_n[2]), .B (n_40), .Q
       (n_47));
  NOR21 g2755__6417(.A (n_10), .B (n_34), .Q (n_45));
  AOI311 g2756__5477(.A (controller_inst_state[0]), .B
       (controller_inst_cnt_m[10]), .C (n_11), .D (n_37), .Q (n_43));
  NOR21 g2757__2398(.A (reset), .B (n_31), .Q (n_42));
  AOI211 g2758__5107(.A (n_18), .B (controller_inst_state[2]), .C
       (n_17), .Q (n_41));
  OAI2111 g2759__6260(.A (controller_inst_cnt_n[0]), .B
       (controller_inst_cnt_n[1]), .C (controller_inst_cnt_n[3]), .D
       (controller_inst_cnt_n[2]), .Q (n_44));
  INV2 g2760(.A (n_38), .Q (n_39));
  INV2 g2761(.A (n_30), .Q (n_37));
  NOR21 g2762__4319(.A (n_17), .B (n_234), .Q (n_32));
  NAND22 g2763__8428(.A (n_18), .B (n_16), .Q (n_31));
  NOR21 g2764__5526(.A (n_14), .B (controller_inst_cnt_n[3]), .Q
       (n_40));
  NOR31 g2765__6783(.A (n_8), .B (controller_inst_state[1]), .C
       (reset), .Q (n_38));
  NAND22 g2766__3680(.A (n_18), .B (controller_inst_state[2]), .Q
       (n_30));
  NOR21 g2767__1617(.A (n_14), .B (controller_inst_cnt_n[2]), .Q
       (n_36));
  NOR31 g2768__2802(.A (controller_inst_cnt_n[0]), .B
       (controller_inst_cnt_n[1]), .C (n_14), .Q (n_35));
  NAND22 g2769__1705(.A (n_19), .B (controller_inst_cnt_m[3]), .Q
       (n_34));
  NOR21 g2770__5122(.A (controller_inst_state[2]), .B (n_18), .Q
       (n_33));
  IMUX20 g2771__8246(.A (lfsr_inst_shift_bits[6]), .B
       (lfsr_inst_shift_bits[5]), .S (n_234), .Q (n_29));
  IMUX20 g2772__7098(.A (lfsr_inst_shift_bits[3]), .B
       (lfsr_inst_shift_bits[2]), .S (n_234), .Q (n_28));
  IMUX20 g2773__6131(.A (lfsr_inst_shift_bits[4]), .B
       (lfsr_inst_shift_bits[3]), .S (n_234), .Q (n_27));
  IMUX20 g2774__1881(.A (lfsr_inst_shift_bits[5]), .B
       (lfsr_inst_shift_bits[4]), .S (n_234), .Q (n_26));
  IMUX20 g2775__5115(.A (lfsr_inst_shift_bits[2]), .B
       (lfsr_inst_shift_bits[1]), .S (n_234), .Q (n_25));
  IMUX20 g2776__7482(.A (scan_chain_in), .B (lfsr_inst_shift_bits[6]),
       .S (n_234), .Q (n_24));
  IMUX21 g2777__4733(.A (n_4), .B (\misr_inst_signature[0]_126 ), .S
       (scan_chain_out), .Q (n_23));
  IMUX20 g2778__6161(.A (lfsr_inst_shift_bits[1]), .B
       (lfsr_inst_shift_bits[0]), .S (n_234), .Q (n_22));
  XNR21 g2779__9315(.A (lfsr_inst_shift_bits[2]), .B
       (lfsr_inst_shift_bits[0]), .Q (n_21));
  INV2 g2780(.A (n_20), .Q (n_19));
  NAND22 g2781__9945(.A (controller_inst_cnt_m[2]), .B
       (controller_inst_cnt_m[1]), .Q (n_20));
  NOR21 g2782__2883(.A (controller_inst_state[0]), .B
       (controller_inst_state[1]), .Q (n_18));
  INV3 g2783(.A (n_15), .Q (n_14));
  NOR21 g2784__2346(.A (controller_inst_state[2]), .B (n_237), .Q
       (n_17));
  NOR21 g2785__1666(.A (n_13), .B (controller_inst_prev_bist_start), .Q
       (n_16));
  NOR21 g2786__7410(.A (reset), .B (controller_inst_cnt_m[10]), .Q
       (n_15));
  INV2 g2787(.A (bist_start), .Q (n_13));
  INV2 g2801(.A (reset), .Q (n_12));
  INV2 g2805(.A (n_236), .Q (n_11));
endmodule

