`timescale 1ns/1ps 
// Generated by Cadence Genus(TM) Synthesis Solution 19.14-s108_1
// Generated on: Dec 15 2025 19:17:35 WET (Dec 15 2025 19:17:35 UTC)

// Verification Directory fv/circuito08 

module circuito08(clock, reset, s, dv, l_in, test_in, fz_L, lclk,
     read_a, test_out, scan_en, scan_in, scan_out);
  input clock, reset, s, dv, l_in, scan_en, scan_in;
  input [1:0] test_in;
  output fz_L, lclk, scan_out;
  output [4:0] read_a;
  output [1:0] test_out;
  wire clock, reset, s, dv, l_in, scan_en, scan_in;
  wire [1:0] test_in;
  wire fz_L, lclk, scan_out;
  wire [4:0] read_a;
  wire [1:0] test_out;
  wire [2:0] cur;
  wire n_0, n_1, n_2, n_3, n_4, n_6, n_7, n_8;
  wire n_9, n_10, n_11, n_12, n_13, n_14, n_15, n_16;
  wire n_17, n_18, n_19, n_20, n_21, n_22, n_23, n_24;
  wire n_25, n_26, n_27, n_28, n_29, n_30, n_32, n_33;
  wire n_34, n_35, n_36, n_37, n_38, n_39, n_40, n_41;
  wire n_42, n_43, n_44, n_45, n_46, n_47, n_48, n_49;
  wire n_50, n_51, n_52, n_53, n_54, n_55, n_56, n_57;
  wire n_58, n_59, n_60, n_61, n_62, n_63, n_64, n_65;
  wire n_66, n_67, n_68, n_69, n_70, n_71, n_72, out3;
  wire out4;
  DFS1 \cur_reg[0] (.C (clock), .D (n_72), .SD (scan_in), .SE
       (scan_en), .Q (cur[0]), .QN (n_12));
  DFS1 \cur_reg[1] (.C (clock), .D (n_70), .SD (n_12), .SE (scan_en),
       .Q (cur[1]), .QN (n_11));
  OAI311 g2126__2398(.A (l_in), .B (n_69), .C (n_41), .D (n_71), .Q
       (n_72));
  DFS1 \cur_reg[2] (.C (clock), .D (n_68), .SD (n_11), .SE (scan_en),
       .Q (cur[2]), .QN (n_10));
  AOI221 g2127__5107(.A (n_67), .B (n_22), .C (n_39), .D (dv), .Q
       (n_71));
  OAI222 g2135__6260(.A (n_65), .B (cur[1]), .C (n_45), .D (n_69), .Q
       (n_70));
  OAI211 g2138__4319(.A (dv), .B (n_40), .C (n_66), .Q (n_68));
  INV3 g2129(.A (n_63), .Q (n_67));
  NAND22 g2139__8428(.A (n_51), .B (n_64), .Q (n_66));
  NAND22 g2140__5526(.A (n_50), .B (n_64), .Q (n_65));
  OAI212 g2130__6783(.A (cur[0]), .B (n_60), .C (n_64), .Q (n_63));
  DFS1 \read_a_i_reg[4] (.C (clock), .D (n_62), .SD (n_7), .SE
       (scan_en), .Q (read_a[4]), .QN (n_9));
  AOI211 g2142__3680(.A (out3), .B (out4), .C (n_69), .Q (n_64));
  AOI211 g2131__1617(.A (n_61), .B (n_58), .C (reset), .Q (n_62));
  DFS1 out4_reg(.C (clock), .D (n_57), .SD (n_0), .SE (scan_en), .Q
       (out4), .QN (n_8));
  DFS1 \read_a_i_reg[3] (.C (clock), .D (n_59), .SD (n_3), .SE
       (scan_en), .Q (read_a[3]), .QN (n_7));
  ADD22 g2133__2802(.A (n_54), .B (n_16), .CO (n_60), .S (n_61));
  DFS1 lclk_i_reg(.C (clock), .D (n_52), .SD (n_10), .SE (scan_en), .Q
       (lclk), .QN (n_6));
  DFS1 \test_out_i_reg[1] (.C (clock), .D (n_53), .SD (n_4), .SE
       (scan_en), .Q (test_out[1]), .QN (scan_out));
  DFS1 \test_out_i_reg[0] (.C (clock), .D (n_49), .SD (n_9), .SE
       (scan_en), .Q (test_out[0]), .QN (n_4));
  AOI211 g2137__1705(.A (n_55), .B (n_58), .C (reset), .Q (n_59));
  NOR21 g2154__5122(.A (reset), .B (n_56), .Q (n_57));
  DFS1 \read_a_i_reg[2] (.C (clock), .D (n_44), .SD (n_2), .SE
       (scan_en), .Q (read_a[2]), .QN (n_3));
  DFS1 \read_a_i_reg[1] (.C (clock), .D (n_48), .SD (n_1), .SE
       (scan_en), .Q (read_a[1]), .QN (n_2));
  DFS1 \read_a_i_reg[0] (.C (clock), .D (n_46), .SD (n_8), .SE
       (scan_en), .Q (read_a[0]), .QN (n_1));
  CLKIN2 g2156(.A (out3), .Q (n_56));
  ADD22 g2141__8246(.A (n_34), .B (n_14), .CO (n_54), .S (n_55));
  NOR21 g2153__7098(.A (reset), .B (n_38), .Q (n_53));
  DFS1 out3_reg(.C (clock), .D (n_33), .SD (n_6), .SE (scan_en), .Q
       (out3), .QN (n_0));
  NOR21 g2149__6131(.A (n_47), .B (n_43), .Q (n_52));
  OAI222 g2150__1881(.A (n_50), .B (n_30), .C (n_29), .D (cur[2]), .Q
       (n_51));
  NOR21 g2152__5115(.A (reset), .B (n_42), .Q (n_49));
  NOR21 g2164__7482(.A (n_27), .B (n_47), .Q (n_48));
  NOR21 g2165__4733(.A (read_a[0]), .B (n_47), .Q (n_46));
  CLKIN3 g2167(.A (n_37), .Q (n_45));
  NOR21 g2148__6161(.A (n_35), .B (n_47), .Q (n_44));
  XOR21 g2155__9315(.A (n_36), .B (lclk), .Q (n_43));
  IMUX20 g2160__9945(.A (test_in[0]), .B (n_24), .S (n_41), .Q (n_42));
  AOI311 g2161__2883(.A (n_28), .B (n_32), .C (n_17), .D (n_39), .Q
       (n_40));
  MUX21 g2162__2346(.A (test_in[1]), .B (n_23), .S (n_41), .Q (n_38));
  OAI212 g2168__1666(.A (dv), .B (n_58), .C (n_41), .Q (n_37));
  NOR21 g2163__7410(.A (n_15), .B (n_36), .Q (n_50));
  NAND22 g2171__6417(.A (n_58), .B (n_19), .Q (n_47));
  ADD22 g2151__5477(.A (n_26), .B (n_13), .CO (n_34), .S (n_35));
  NOR31 g2169__2398(.A (n_25), .B (n_20), .C (reset), .Q (n_33));
  NOR40 g2170__5107(.A (n_69), .B (cur[0]), .C (n_32), .D (n_21), .Q
       (n_39));
  NOR20 g2173__6260(.A (cur[0]), .B (n_30), .Q (fz_L));
  NAND41 g2166__4319(.A (n_18), .B (read_a[3]), .C (read_a[4]), .D
       (read_a[0]), .Q (n_36));
  OAI2111 g2172__8428(.A (cur[0]), .B (cur[1]), .C (n_29), .D (n_32),
       .Q (n_41));
  NAND22 g2175__5526(.A (n_29), .B (n_30), .Q (n_58));
  INV0 g2179(.A (n_69), .Q (n_28));
  AOI211 g2174__6783(.A (read_a[1]), .B (read_a[0]), .C (n_26), .Q
       (n_27));
  IMUX21 g2177__3680(.A (n_24), .B (test_out[0]), .S (test_in[0]), .Q
       (n_25));
  IMUX20 g2178__1617(.A (test_out[0]), .B (n_24), .S (test_out[1]), .Q
       (n_23));
  INV2 g2183(.A (n_30), .Q (n_22));
  NAND22 g2186__2802(.A (n_21), .B (cur[2]), .Q (n_30));
  XOR21 g2176__1705(.A (test_in[1]), .B (test_out[1]), .Q (n_20));
  NAND20 g2182__5122(.A (n_19), .B (s), .Q (n_69));
  NOR21 g2180__8246(.A (read_a[1]), .B (read_a[2]), .Q (n_18));
  NAND22 g2185__7098(.A (cur[1]), .B (cur[0]), .Q (n_29));
  NOR21 g2184__6131(.A (cur[0]), .B (cur[1]), .Q (n_17));
  NOR21 g2181__1881(.A (read_a[0]), .B (read_a[1]), .Q (n_26));
  INV2 g2190(.A (read_a[4]), .Q (n_16));
  INV2 g2193(.A (cur[0]), .Q (n_15));
  INV2 g2191(.A (cur[1]), .Q (n_21));
  INV0 g2194(.A (reset), .Q (n_19));
  INV3 g2187(.A (read_a[3]), .Q (n_14));
  INV3 g2188(.A (read_a[2]), .Q (n_13));
  INV3 g2189(.A (cur[2]), .Q (n_32));
  INV3 g2192(.A (test_out[0]), .Q (n_24));
endmodule

